spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: sumishaCoolminds@gmail.com
    password: sumishak@1995
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            enable: true


